### ISSUE TITLE
Working only if the message fits the space

### ISSUE THREAD

**Issue by lucmos** [nexes/statusbar-error#1]
Currently it works only if the message fits the available space.
It would be nice to have the message always displayed.

Possible solutions may be:

* Make the sentences that do not fit slide in a cyclic way
* Reduce the size of the font so that it can fit
* Popup a bar a the bottom to display the message, if it doesn't fit

**Comment by nexes** [comment]
I agree and it's something I've been thinking about. There are a few problems though. 

- When vscode is resized smaller, it will start removing status bar items as it goes and brings them back when the window gets larger. So I can't make the text scroll if there is no status bar item to display it (when the window is to small or not large enough depending on how many items a user has in the status bar).

- With the current API, there isn't a good way to change the font style in the status bar.

- I've been playing with displaying them in popup messages, the problem is they become "stacked" on each other and there isn't a good way for me to clear them programmatically when the user moves around the file. I've also been playing around with displaying them in an output panel (where you find the terminal, debugger etc) but that has it's own UI issues.

I'll keep this issue open and keep working on it.

Thanks
